### ISSUE TITLE
Error on Bittensor Installlation- Using /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/opentensor/bittensor/master/scripts/install.sh)"

### ISSUE THREAD

**Issue by iammeharg** [opentensor/developer-docs#148]
**Error on Bittensor Installlation**

error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
"" command failed with exit code 1.

**Comment by iammeharg** [comment]
Please ssupport to resolve

**Comment by rajkaramchedu** [comment]
@iammeharg On which type of machine are you trying to install? Linux or Mac? Please post the OS type and OS version. Thanks.

**Comment by iammeharg** [comment]
ubuntu on windows 11 WSL

**Comment by rajkaramchedu** [comment]
So your system is mostly standard. The error above tells you exactly what the issue is. You can check the PATH for Rust or to get you moving forward quickly, try other methods of installation described in https://docs.bittensor.com/getting-started/installation. Also for quicker responses, please use Bittensor Discord and ask questions there. After you figure out what could be the problem, please update this Issue and I will update the docs, if needed.
